### PR TITLE
Don't overwrite ChunkPrimer#setBlockState - compat for VSD

### LINKED ISSUE #81: Class Transformer collision in ChunkPrimer with mod Vertically Stacked Dimensions
I have an [issue with my mod](https://github.com/CD4017BE/VerticallyStackedDimensions/issues/15) when it is installed together with JEID.

My mod does a [small modification](https://github.com/CD4017BE/VerticallyStackedDimensions/blob/master/src/java/cd4017be/dimstack/asm/ChunkPrimerTransformer.java) to the `ChunkPrimer` class that is essential for its bedrock (or any other block) generation prevention feature. The problem is that - how I understand your code (don't know how that spongepowered mixin stuff you're using exactly works) - JEID completely replaces that class with it's own implementation.

This is the relevant part of the log:
```
[00:44:41] [Client thread/TRACE] [FML]: Sending event FMLPreInitializationEvent to mod dimstack
[00:44:41] [Client thread/INFO] [dimstack]: Testing ClassTransformer result of class cd4017be.dimstack.asm.ChunkPrimerTransformer for correct functionality ...
[00:44:41] [Client thread/DEBUG] [VSD ASM]: patching ChunkPrimer as net/minecraft/world/chunk/ChunkPrimer ...
[00:44:41] [Client thread/DEBUG] [VSD ASM]: patching method setBlockState() as func_177855_a(IIILnet/minecraft/block/state/IBlockState;)V
[00:44:41] [Client thread/DEBUG] [VSD ASM]: adding field ingnoredBlock
[00:44:41] [Client thread/DEBUG] [mixin]: Mixing MixinChunkPrimer from mixins.jeid.core.json into net.minecraft.world.chunk.ChunkPrimer
[00:44:41] [Client thread/TRACE] [mixin]: Added class metadata for net/minecraft/util/ObjectIntIdentityMap to metadata cache
[00:44:41] [Client thread/INFO] [dimstack]: dryTest passed!
[00:44:41] [Client thread/DEBUG] [VSD ASM]: patching BlockPredicate ...
[00:44:41] [Client thread/DEBUG] [VSD ASM]: patching method disableBlock() as disableBlock(Lnet/minecraft/world/chunk/ChunkPrimer;Lnet/minecraft/block/state/IBlockState;)V
[00:44:41] [Client thread/FATAL] [dimstack]: mainTest failed! Please report this to the mod author!
java.lang.Exception: Blacklisted block was placed: expected minecraft:stone@0 but got minecraft:obsidian@0.
```
`VSD ASM` is my class transformer and `dimstack` is my main mod running its tests.

### PR DESCRIPTION
**Pull request by sk2048**
Closes #81

### CODE REVIEW

**Comment by sk2048** [comment]
As described here: https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/81#issuecomment-520107470

**Comment by ZombieHDGaming** [comment]
@sk2048 Does the normal behavior still happen with this change? As for the release with these fixes, I need to finish up JEIDsI fixes included and appreciate if you could help out since you know your fixes better than I do lol

**Comment by sk2048** [comment]
Yes, without any other mods present ChunkPrimer#setBlockState becomes

```java
public  void setBlockState(int x, int y, int z, IBlockState state) {
  CallbackInfo ci = new CallbackInfo("setBlockState");
  setIntBlockState(x, y, z, state, ci);
  if (ci.isCancelled()) return;
  // Normal vanilla code (dead)
}
```

And setIntBlockState just

```java
private void setIntBlockState(int x, int y, int z, IBlockState state, CallbackInfo ci) {
  intData[getBlockIndex(x, y, z)] = Block.BLOCK_STATE_IDS.get(state);		    
  ci.cancel();
}
```

It's ever so slightly more overhead, but far more resilient to other people making changes to it.

**Comment by ZombieHDGaming** [comment]
If it makes mods more compatible, I'm all for it. And we can talk on Discord about what needs fixing with the included fixes of JEIDsI and what still needs to be ported.

**Pull request merged**
