### PR TITLE
Fix mod incompatibility with mods that redirect generateChunk.

### PR DESCRIPTION
**Pull request by Zidane**
Since NotEnoughIDs isn't changing generateChunk and, instead, is only
changing the biome array, we can safely inject afterwards.

Addresses incompatibility with SpongeForge.

Signed-off-by: Chris Sanders <zidane@spongepowered.org>

### CODE REVIEW

**Comment by Zidane** [comment]
Just to clarify a bit, the problem was exposed because we're trying to continue to prune our overwrites to a minimum (as Overwrites add a lot more maintenance on our end and have burned us badly in the past when moving between Minecraft major versions). SpongeForge redirects the generateChunk call and so do you folks but we happen to have a higher priority so yours gets removed from being called. This addresses this so that both mods are happy.

**Comment by Zidane** [comment]
Found a possible issue, one sec (don't merge quite yet).

**Comment by Zidane** [comment]
There we go, good to go now.

**Comment by Runemoro** [comment]
Thanks!

**Pull request merged**
